# Generated by Django 4.1.6 on 2023-02-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_rename_assigned_to_project_owner"),
        ("tickets", "0002_ticket_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickettype",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="types",
                to="projects.project",
            ),
            preserve_default=False,
        ),
    ]
