# Generated by Django 4.1.6 on 2023-02-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_tickettype_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("immediate", "Immediate"),
                ],
                default="normal",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In progress"),
                    ("closed", "closed"),
                ],
                default="open",
                max_length=100,
            ),
        ),
    ]
